# Generated by Django 5.2.6 on 2026-05-19 19:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_type', models.CharField(max_length=32)),
                ('format', models.CharField(default='csv', max_length=8)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('file_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manager_analytics_export_job',
            },
        ),
    ]
